### ISSUE TITLE
model

### ISSUE THREAD

**Issue by xiaowowwwww** [jjhuangcs/WINNet#2]
Hello, I have some questions that have been showing no module named iUNet.I want to know what's going on, thank you!

**Comment by jjhuangcs** [comment]
Hi, you can find iUNet in the folder of utils.

**Comment by xiaowowwwww** [comment]
Hi, I see that, but the runtime keeps showing this error message.

**Comment by xiaowowwwww** [comment]
![image](https://github.com/jjhuangcs/WINNet/assets/138083719/9f2b0c96-dac5-4cb2-a895-a36dd57208ae)

**Comment by jjhuangcs** [comment]
I did not encounter this issue before, maybe this could be due to your path setting problem. I suggest you try to google "no module named" and find a solution for that.

**Comment by xiaowowwwww** [comment]
Thank you for your reply. I have solved the problem.
